const allPrompts = [
    // Your 43 Original Prompts:
    "Cover up the emotions of your character in the scene by using the opposite emotion instead.",
    "Do the scene as if you are on a really intense rollercoaster.",
    "Before you say each line, look into your scene partner's eyes first to see if you can read your next line in them.",
    "Say every line as if you are carefully thinking about how to say it to your scene partner before actually speaking it.",
    "Start the scene laughing and end the scene sighing.",
    "Make sure your scene partner understands everything you are saying because it is that important.",
    "Switch roles to understand the scene deeper.",
    "Make one word out of every line have an isolated emphasis with volume or tone.",
    "Delay saying your first line until the very last moment before it would be painfully awkward to witness.",
    "Give every single word you say intention and importance.",
    "Obviously lie at one point and let us see you do not think you got away with it.",
    "Be responsible for making the scene peak with intensity at least once, if not twice.",
    "Play the role like its cartoon or anime version might be portrayed.",
    "Thoughtfully use three different 'persuasive techniques' to get what you want.",
    "Play the scene as if you were the President.",
    "Find two ways to mock your scene partner in the scene.",
    "Play the role like your favorite sitcom character.",
    "Describe five words in the scene in the way you deliver the words.",
    "Every word in a line that requires emphasis, you should draw out the vowel. (e.g., \"That puppy is SOOOOOO cute!\")",
    "Forget every choice you have already made and let the choices of your scene partner dictate how you will deliver your response.",
    "Use your best British accent this time.",
    "Get strongly frustrated without warning.",
    "Act out the 30 seconds before the scene and 30 seconds after it ends.",
    "Try it like a redneck country bumpkin.",
    "Write down another way of wording your lines that gives a reason why you are saying it. Then say the original line as a substitute for that secondary meaning.",
    "Play the scene as if it were a contrasting genre (e.g., play it for laughs if it's a drama).",
    "Choose 1 or 2 lines in the scene to sing instead of speak.",
    "Improv additional dialogue in the scene but only use noises.",
    "Play the scene as the most annoying person you know.",
    "Try to say every line completely different than you have before.",
    "Take it up three whole levels and find two things that actually worked with the amplification.",
    "Get lost in one of your character's memories at some point.",
    "Spend the scene trying to figure out why your scene partner's eyes look so familiar.",
    "Look around the imaginary space and notice details you have never seen before.",
    "Use a very big physical gesture to create emphasis in one of your lines.",
    "Do the scene as if you just found out from your doctor that you had only a few days left to live.",
    "At some point in the scene, do a dance.",
    "Discover partway into the scene that you are actually totally in love with your scene partner.",
    "Use instrumental music to get you to feel the tone of the scene.",
    "Play it ghetto this time.", // Consider rephrasing for sensitivity
    "Play it like you are in a different era than the scene is supposed to be set in.",
    "This time, do the scene as if you have to pee really bad.",
    "Do the scene as if you absolutely did not want anyone in the next room to hear this conversation.",

    // 56 New Prompts:
    "Secret Urgency: Perform the scene as if you have a critical, secret ticking clock that only you know about (e.g., you must leave in exactly 2 minutes).",
    "Hidden Physical Discomfort: Play the scene as if something is physically uncomfortable (a tag in your shirt, a rock in your shoe, a burgeoning headache) that you're trying to hide.",
    "Pervasive Suspicion: Do the scene as if you deeply suspect the other character is lying about something fundamental, even if the script offers no direct evidence.",
    "Barely Contained Joy: Play the scene as if you've just received incredibly good news, but you absolutely cannot reveal it yet.",
    "Masked Terror: Perform the scene as if you are secretly terrified (of the other character, the situation, or something unsaid) but are desperately trying to appear brave or normal.",
    "Invisible Confidant: Play the scene as if your character has an invisible friend or advisor they are subtly consulting, reacting to, or trying to protect.",
    "Premonition: Do the scene as if your character has a strong premonition about how this conversation will end (either very well or very badly) and is actively trying to change or ensure that outcome.",
    "Life is a Game: Treat every line and interaction in the scene as moves in a high-stakes game that your character is determined to win.",
    "Fresh Emotional Wound: Play the scene as if your character is nursing a recent, deep emotional wound that everything in the current situation keeps aggravating.",
    "Exaggerated Courtesy: Deliver all your lines with an almost unsettling level of exaggerated politeness and formality, regardless of the emotional content.",
    "Is My Scene Partner a Spy?: Play the scene with the sudden, dawning suspicion that your scene partner might be a spy or has a hidden, dangerous agenda.",
    "Desperate for Approval: Perform the scene as if it's incredibly important to your character that the other character likes, respects, and approves of them.",
    "Secretly Famous/Accomplished: Do the scene as if your character has a secret major achievement (e.g., just won an award, is secretly a genius) and is bursting with understated pride or knowledge.",
    "Everything's a Slight: Interpret every line, gesture, or even pause from your scene partner as a subtle (or not-so-subtle) insult or criticism.",
    "Covert Mission: Your character has a small, secret physical mission they must accomplish during the scene without the other character noticing (e.g., retrieve a hidden item, leave a secret note).",
    "Mesmerizing Delivery: Try to deliver your lines in such a way that your voice and presence are almost hypnotic or deeply captivating to your scene partner.",
    "Delusion of Control: Play the scene as if your character *believes* they are subtly controlling their scene partner's thoughts and actions through sheer willpower or manipulation.",
    "Objective: Must Not Cry: Your character's primary objective in this scene is to not break down and cry, no matter how overwhelming the emotions become.",
    "Objective: Must Not Laugh: Your character's primary objective is to not laugh, even if the situation or the other character is absurdly funny or trying to make them break.",
    "Ultimate Authority on This Subject: Play your character as if they are the undisputed world's foremost expert on the central topic of the scene.",
    "Utterly Clueless (But Faking It): Play your character as if they have absolutely no idea what is truly going on but are desperately trying to pretend they are in full understanding and control.",
    "Physicalize One Internal Thought: Choose one key internal thought or feeling of your character and find a subtle, recurring physical gesture or tic that expresses it.",
    "Momentary Mirroring: At a key moment, subtly mirror a specific physical gesture, posture, or vocal inflection of your scene partner.",
    "Intense Focus on an Inanimate Object: Pick an ordinary object (real or imagined) and imbue it with immense significance, focusing on it intensely at certain moments.",
    "Radical Honesty (No Subtext): Play the scene with absolutely no subtext; every emotion, thought, and intention is 100% on the surface and clearly expressed.",
    "Lead With a Specific Body Part: Choose one body part (e.g., your chin, one shoulder, your hands) and let it consistently lead your character's movements and intentions.",
    "Subtle Animalistic Quality: Choose an animal that resonates with your character's core nature and subtly incorporate its physicality, energy, or vocal quality.",
    "Borrow a Distinctive Mannerism: Think of a famous person, a historical figure, or another fictional character and borrow one of their specific, recognizable mannerisms for this scene.",
    "Slow-Burn Emotion: When a strong emotion is indicated, allow it to build internally in a \"slow-burn\" fashion before it fully manifests in your lines or actions.",
    "The Impact of Absolute Stillness: Find one or two moments in the scene to become completely, intensely still and focused, creating a powerful contrast to any surrounding action.",
    "The Ground Beneath You is...: Play the scene with the underlying physical awareness that the floor is something unusual (e.g., slippery ice, scorching sand, marshmallows), subtly affecting your balance and movement.",
    "Concealed Superpower: Act as if your character possesses a secret superpower that they are consciously and carefully trying *not* to use or reveal during the scene.",
    "Whisper a Power Line: Choose a line that would typically be delivered with force or volume and instead whisper it with profound intensity.",
    "Unexpected Emphasis on a Mundane Line: Choose a seemingly unimportant or quiet line and deliver it with surprising volume, speed, or emotional weight.",
    "Breath as a Strategic Tool: Use your breath very consciously: a sharp intake for surprise, holding your breath for tension, a sigh to release (or feign) an emotion.",
    "Perceive Scene Partner as a Child: Regardless of their actual age or role, interact with your scene partner as if they are a small, perhaps naive or unruly, child you must patiently guide, protect, or explain things to.",
    "Perceive Scene Partner as Immensely Powerful: Treat your scene partner as if they are incredibly high-status (royalty, a fearsome boss, a deity) or someone who holds significant, unspoken power over you.",
    "Embody an Element of Nature: Choose an element of nature or weather (a brewing storm, oppressive humidity, bright sunshine, an earthquake tremor) and let that quality infuse your character's mood, rhythm, and physicality.",
    "Secret Emotional Anchor to an Object: Your character has a secret, intense emotional attachment (positive or negative) to an inanimate object in the scene or on their person, and it influences their reactions.",
    "Everything is Utterly New: React to your surroundings, the situation, and even familiar lines from your scene partner as if you are experiencing everything for the very first, fascinating, or bewildering time.",
    "Selective Auditory Focus: Play the scene as if you are only truly hearing and processing certain words or phrases from your scene partner, and your mind is filling in the (perhaps incorrect) blanks.",
    "Distorted Perception: Play the scene as if your character's perception is slightly off (vision is blurry, sounds are distorted, sense of time is warped) but they're trying to function normally.",
    "Invisible Physical Irritant: Act as if there's something constantly, physically annoying your character that no one else can see or acknowledge (e.g., an invisible insect, a persistent itch under their skin).",
    "Undercover Recording: Perform the scene as if your character is secretly recording the interaction (audio or video) for a vital, personal reason they cannot disclose.",
    "Overpowering Olfactory Reaction: Act as if your scene partner (or the environment) is emitting a very distinct and powerful scent (amazingly attractive or deeply repulsive) that strongly affects your character's behavior and focus.",
    "Persistent Mental Loop: Your character has a song, jingle, random phrase, or image stuck in their head on a loop, and it's subtly influencing their rhythm, mood, or distracting them.",
    "Am I Dreaming This?: Play the scene as if your character is fairly certain they are in a dream and is cautiously (or boldly) testing the reality of the situation and its consequences.",
    "Manipulated by Unseen Forces: Imagine your character's movements and some impulses are being subtly manipulated by invisible marionette strings, controlled by an unseen puppeteer with their own agenda.",
    "This Prop is My Lifeline: Choose a prop (real or imaginary) and make it your character's absolute lifeline – their source of comfort, power, or the only thing keeping them grounded in the scene.",
    "Simultaneous Mundane Task: While delivering your lines, your character is also seriously focused on completing a small, unrelated, and perhaps slightly challenging physical task (e.g., trying to untie a difficult knot, meticulously folding a piece of paper into a complex shape).",
    "Master of Misdirection: Say all your lines as if you are an expert in reverse psychology or misdirection, carefully choosing your words to make your scene partner believe or do the opposite of what you overtly state.",
    "Frantic Concealment: Your character is trying to hide a small, significant object on their person (or in the immediate vicinity) without the other character noticing, and this effort underlies all their actions.",
    "The Weight of an Unseen Observer: Act as if someone whose opinion your character values immensely (or fears greatly) is secretly watching their every move and word.",
    "Driven by an Internal Rhythm: Create a very specific internal rhythm (e.g., a frantic ticking clock, a slow, heavy heartbeat, a joyful, skipping melody) and let it powerfully influence the pace, energy, and emotional state of your character.",
    "Thoughts in Another Language: Even if the scene is in your native language, play the character as if their internal thought process is happening in a different language, and they are carefully (or sometimes awkwardly) translating into the language of the scene.",
    "Invisible Barrier/Pull: Imagine there's an invisible force field or magnetic pull/repulsion between you and your scene partner (or an object) that changes in strength, making it physically challenging to get closer or move away at certain moments."
];
